### ISSUE TITLE
Sometimes a note remains inscribed

### ISSUE THREAD

**Issue by mia8888** [collinss/sticky#4]
Hello,

I just read the September 2020 monthly news from the linuxmint blog, in which Clem asks:
"Sticky Notes
We are also seeking comments on "Sticky Notes," a side project developed by Stephen Collins. "
I do not understand English well and I am posting for the first time on a software problem, I just signed up on github for the bug, please excuse my mistakes.
I have used sticky notes for several months, but replaced it a few days ago because I often encounter an annoying problem.
Sometimes, not always, when I move a note it stays under the mouse pointer. I have to click to put it back.
When this happens, often the note is no longer movable afterwards and remains above all windows.
We can't shut it down.
It also happens that it duplicates itself when I want to slip it elsewhere and it stays stuck in its place
It only disappears when I restart the computer.
Hope I explained to you correctly, I am using a translator.

Have a good day.
Mia

**Comment by collinss** [comment]
I believe you are referring to the sticky notes applet that is currently available for Cinnamon (which I also wrote). It had several annoying bugs, that weren't really fixable, including one where the notes would sometimes get stuck to the mouse like you described. This is actually a different project. Part of the reason I started this project was because of those bugs. If you'd like to try it, you can follow the instructions in the [readme](https://github.com/collinss/sticky/blob/master/README.md). I'd be interested to see how you think it compares to the applet.

**Comment by mia8888** [comment]
I was talking about the applet actually, I didn't understand that this is a different project, sorry.
I am still with Mint 19.3 for a while, and have uploaded my notes to tiddlywiki.
I'll be sure to try out your new sticky notes project when I upgrade to Mint 20 and say what's better than the applet.
Cdt

**Comment by collinss** [comment]
Ok, I'm going to close this then. You're still welcome to use this thread later, our you can leave your feedback elsewhere. Also, please note that this project isn't currently available in any version of Mint, but I'm hoping it gets included in Mint 20.1.

**Comment by mia8888** [comment]
Noted.
Thank you for your investment in the Mint community :+1:
